name: 'Frontend CI'

# Run this workflows on pull requests against Main branch and enable manual trigger
on:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  # Linting
  linting:
    runs-on: ubuntu-latest
    steps:
      # Check out frontend code
      - name: Checkout frontend code
        uses: actions/checkout@v3
      
      # Setup Node JS
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      # Perform cache action

      # Install dependencies
      - name: Install dependencies
        run: cd starter/frontend && npm ci

      # Run linting
      - name: Run linting
        run: cd starter/frontend && npm lint

  # Testing
  testing:
    runs-on: ubuntu-latest
    steps:
      # Check out frontend code
      - name: Checkout frontend code
        uses: actions/checkout@v3
      
      # Setup Node JS
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      # Perform cache action

      # Install dependencies
      - name: Install dependencies
        run: cd starter/frontend && npm ci

      # Run tests
      - name: Run linting
        run: cd starter/frontend && npm run test

  # Building only if above 2 pass
  building:
    needs: [linting, testing]
    runs-on: ubuntu-latest
    steps:
      # Check out frontend code
      - name: Checkout frontend code
        uses: actions/checkout@v3
      
      # Setup Node JS
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      # Perform cache action

      # Install dependencies
      - name: Install dependencies
        run: cd starter/frontend && npm ci

      # Run build
      
    
    